import React from 'react';
import type { Metadata } from 'next';

// eslint-disable-next-line camelcase
import { Geist, Geist_Mono, Rethink_Sans } from 'next/font/google';

import '@repo/ui/globals.css';
import Providers from '../providers/SessionProvider';
import QueryProvider from '../providers/QueryClientProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const rethinkSans = Rethink_Sans({
  variable: '--font-rethink-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} ${rethinkSans.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className='min-h-full flex flex-col'>
        <Providers>
          <QueryProvider>
            <main className='flex-1'>{children}</main>
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
